// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbL8WrUzHGQwerfyGFwfDJ5Pi4YWbqeyg',
    appId: '1:659088466351:web:31a291e1196849ee114f5a',
    messagingSenderId: '659088466351',
    projectId: 'frontagenda1',
    authDomain: 'frontagenda1.firebaseapp.com',
    storageBucket: 'frontagenda1.firebasestorage.app',
    measurementId: 'G-ZRS2W0FEQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAutwv4PRRKZlKcsv5mKMHxtMykJQmwXCQ',
    appId: '1:659088466351:android:4b781c0f16956268114f5a',
    messagingSenderId: '659088466351',
    projectId: 'frontagenda1',
    storageBucket: 'frontagenda1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK2pJHZaUKCWYU2l8oP9oIbMp6Yr3iJA0',
    appId: '1:659088466351:ios:d1e6afae4cd41568114f5a',
    messagingSenderId: '659088466351',
    projectId: 'frontagenda1',
    storageBucket: 'frontagenda1.firebasestorage.app',
    iosBundleId: 'com.example.agendaAcademicaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK2pJHZaUKCWYU2l8oP9oIbMp6Yr3iJA0',
    appId: '1:659088466351:ios:d1e6afae4cd41568114f5a',
    messagingSenderId: '659088466351',
    projectId: 'frontagenda1',
    storageBucket: 'frontagenda1.firebasestorage.app',
    iosBundleId: 'com.example.agendaAcademicaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbL8WrUzHGQwerfyGFwfDJ5Pi4YWbqeyg',
    appId: '1:659088466351:web:a9da22e6cbae51cb114f5a',
    messagingSenderId: '659088466351',
    projectId: 'frontagenda1',
    authDomain: 'frontagenda1.firebaseapp.com',
    storageBucket: 'frontagenda1.firebasestorage.app',
    measurementId: 'G-KEBG225HF7',
  );
}
